# States all stages
stages:
  - build
  - test
  - deploy

# Compiles the web application and caches the Maven dependencies and target files
build:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_NAME! Compiling the web application."

# Runs unit tests for the web application and caches the Maven dependencies and target files
# Ensures the application behaves as expected before proceeding since all stages after this require test stage to complete successfully
test:
  stage: test
  script:
    - echo "Testing the web application."

deploy:
  stage: deploy
  script:
    - echo "Deploying the web application."
  # Runs the job only when a commit to master has been made
  only:
    - master
